# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 322e3d8a25e837a704816e2bcaf47c16c34fa73363a45cad3f265ed8c44f31e935fffcd6cc985601c9c1f07eee646626bfe97c772a75005c13eb378ddd3b1770

test:
  secret_key_base: a68eb6e6574e8522b63cded81f3fc0a93b4fa578dd2c92456959b7b72e4592cbade60836f03912edbcb1604bc77442a05e79d8bf37f3b7aa98c19b6dd8453dfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
